from .checker import CheckSolution
from .test01 import TaskOne
from .test02 import TaskTwo
from .test03 import TaskThree
from .test04 import TaskFour
from .test05 import TaskFive
from .test06 import TaskSix
from .test07 import TaskSeven
from .test08 import TaskEight
from .test09 import TaskNine
from .test10 import TaskTen
from .test11 import TaskEleven
from .test12 import TaskTwelve
from .test13 import TaskThirteen
from .test14 import TaskFourteen
from .test15 import TaskFifteen
from .test16 import TaskSixteen
from .test17 import TaskSeventeen
from .test18 import TaskEighteen
from .test19 import TaskNineteen
from .test20 import TaskTwenty